import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer, Header, SiteLink } from "../../components/SiteChrome";
import { Markdown } from "../../components/Markdown";
import { formatDate, getFieldNote, getFieldNotes } from "../../../lib/field-notes";

export function generateStaticParams(){ return getFieldNotes().map(({slug})=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const note=getFieldNote((await params).slug); if(!note)return{}; return {title:`${note.title} | Good Move Field Notes`,description:note.excerpt,openGraph:{title:note.title,description:note.excerpt,images:[]},twitter:{title:note.title,description:note.excerpt,images:[]}}; }
export default async function NotePage({params}:{params:Promise<{slug:string}>}) { const note=getFieldNote((await params).slug); if(!note)notFound(); return <><Header/><main id="main-content"><article className="note"><header><SiteLink href="/field-notes">← All Field Notes</SiteLink><p className="eyebrow">Field Note {note.number}</p><h1>{note.title}</h1><p>{note.excerpt}</p><div className="note-meta"><span>By Joe Martin</span><time dateTime={note.date}>{formatDate(note.date)}</time><span>{note.readingMinutes} min read</span></div></header><div className="prose"><Markdown source={note.body}/>{note.reflection && <aside className="reflection" aria-labelledby="reflection-heading"><p className="eyebrow">Pause and consider</p><h2 id="reflection-heading">Leadership Reflection</h2><p>{note.reflection}</p></aside>}</div></article><section className="note-cta"><h2>Where could your organization become more capable?</h2><SiteLink className="button" href="/contact">Schedule a Capability Conversation <span>↗</span></SiteLink></section></main><Footer/></>; }
