import type { Metadata } from "next";
import { Footer, Header, SiteLink } from "../components/SiteChrome";
export const metadata: Metadata = { title: "Operations Clarity Sprint | Good Move Consulting", description: "A focused engagement to understand one high-friction workflow, identify bottlenecks, and give your team a practical path to stronger execution." };
const outcomes = [
 ["01", "A shared view of the work", "A current-state workflow showing how work moves, who owns each step, and where decisions and handoffs happen."],
 ["02", "Clarity on what gets in the way", "An analysis of bottlenecks, recurring workarounds, and dependencies, grounded in what your team is experiencing."],
 ["03", "A more capable future state", "A proposed workflow with clearer ownership, stronger handoffs, and the documentation needed to support it."],
 ["04", "A practical path forward", "A prioritized implementation roadmap that identifies next steps, responsibilities, and ways to assess progress."],
];
export default function Sprint() { return <><Header/><main id="main-content">
<section className="page-hero"><p className="eyebrow">Our primary engagement</p><h1>Operations Clarity Sprint</h1><p>Understand what is slowing one important workflow—and what your team can do about it.</p><div className="actions"><SiteLink className="button" href="/contact">Schedule a Capability Conversation <span aria-hidden="true">↗</span></SiteLink></div></section>
<section className="two-col"><div><p className="eyebrow">When the Sprint fits</p><h2>The same friction keeps coming back.</h2></div><div><p>Work stalls between teams. Decisions wait on one person. A reliable employee holds a fragile process together. Everyone is busy, but the same problems keep returning.</p><p>The Sprint focuses on one workflow where that friction matters: for example, client onboarding, service delivery, internal approvals, or reporting. Together, we agree on the boundaries and the question the engagement needs to answer.</p><p>The result is a shared understanding of the problem and a practical plan for improving the work.</p></div></section>
<section className="section-intro"><p className="eyebrow">What you leave with</p><h2>Clarity your team can act on.</h2></section><section className="steps">{outcomes.map(([n,title,copy])=><article key={n}><span>{n}</span><h2>{title}</h2><p>{copy}</p></article>)}</section>
<section className="two-col"><div><p className="eyebrow">How the engagement works</p><h2>Focused scope. Close collaboration.</h2></div><div><p>We begin by agreeing on one workflow, the people involved, and the information available. We listen to the people doing the work, review the process and supporting materials, and trace where friction builds.</p><p>We then review the findings with your team, develop a future-state workflow, and agree on a prioritized roadmap. Scope, timing, and fee are confirmed before the engagement begins.</p><p>The Sprint provides the diagnosis and plan. Any implementation support is scoped separately, so you can decide what to take on internally and where help would be useful.</p></div></section>
<section className="two-col"><div><h2>Capability first. Tools in service of the work.</h2></div><div><p>A clearer decision, a better handoff, or a documented process may do more than another platform. Automation and AI enter the recommendation when they support a specific need, with appropriate human judgment and ownership.</p><p>Every recommendation starts with how your organization needs to work.</p></div></section>
<section className="note-cta"><div><p className="eyebrow">Start with a conversation</p><h2>Where does work feel harder than it should?</h2><p>In about 30 minutes, we will explore the friction and whether a Sprint is the right next step.</p></div><SiteLink className="button" href="/contact">Schedule a Capability Conversation <span aria-hidden="true">↗</span></SiteLink></section>
</main><Footer/></>; }
